modLoader="javafml"
loaderVersion="[43,)"
license="The Unlicensed"

[[mods]]
modId="simple_item_block_mod"
displayName="Simple Item Block Mod"
version="${file.jarVersion}"
description="Add Simple Item and Simple Block"
logoFile="icon.png"

[[dependencies.simple_item_block_mod]]
modId="forge"
versionRange="[43,)"
mandatory=true

[[dependencies.simple_item_block_mod]]
modId="minecraft"
versionRange="[1.19.2,1.20)"
mandatory=true