modLoader="javafml"
loaderVersion="[43,)"
license="The Unlicensed"

[[mods]]
modId="tutorial"
displayName="Template Mod"
version="${file.jarVersion}"
description="Tutorial Mod for Forge"
logoFile="icon.png"

[[dependencies.tutorial]]
modId="forge"
versionRange="[43,)"
mandatory=true

[[dependencies.tutorial]]
modId="minecraft"
versionRange="[1.19.2,1.20)"
mandatory=true