modLoader="javafml"
loaderVersion="[43,)"
license="The Unlicensed"

[[mods]]
modId="event_bus_check"
displayName="Event Bus Check Mod"
version="${file.jarVersion}"
description="Check Each Event Bus Behabiour"
logoFile="icon.png"

[[dependencies.event_bus_check]]
modId="forge"
versionRange="[43,)"
mandatory=true

[[dependencies.event_bus_check]]
modId="minecraft"
versionRange="[1.19.2,1.20)"
mandatory=true